### PR TITLE
HQLPARSER-53 Join on embedded collections

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/HQLPARSER-53

This patch will enable the support of join operation.

I've chenged the parsed and now the sub-tree related to a join is the following:

```
(property-join INNER a (PATH (. e author)))))
```

instead of 

```
(property-join INNER a (PROPERTY_REFERENCE (. e author)))))
```

This way I can register the property path and the alias via the new method `delegate.registerJoinAlias(Tree alias, PropertyPath propertyPath)`

This method is invoked when the new rule *joinPropertyReference* in GeneratedHQLResolver.g and QueryRenderer.g is called.

@gunnarmorling, @Sanne  It seems to pass all the test but let me know if I missed something

### CODE REVIEW

**Comment by DavideD** [comment]
I think we should wait to merge this (I'm having some errors while using it with OGM) but I would like to know if you think the approach is correct.

**Comment by Sanne** [comment]
I'll have a look

**Comment by DavideD** [comment]
@Sanne sorry, I've just seen your comment now. I've applied a few changes and rebased to fix some error I have encountered:

* Added some more tests to check embedded used with operator (IN, BETWEEN, ...)
* Added some more tests to check embedded used in projections with unqualified properties
* Fix error related to projections in `LuceneQueryRendererDelegate#setPropertyPath(PropertyPath)`
* Fix error where aliases were not resolved for some predicates in `SingleEntityQueryRendererDelegate`

**Comment by Sanne** [comment]
rebased & merged

**Pull request closed without merging**
