### PR TITLE
Fix checkstyle violations

### PR DESCRIPTION
**Pull request by DavideD**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Looks good. Can you merge it yourself :) Thx!

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-hql-parser/pull/28

**Comment by DavideD** [comment]
I was surprise to see the build fail. Don't we run it on CI?

**Comment by gunnarmorling** [comment]
There are jobs: http://ci.hibernate.org/view/Parser/

But for whatever awkward reason they don't seem to have any actual build job. Very weird. Could you take a look into those if you have a minute?

**Comment by gunnarmorling** [comment]
E.g. for the master job, the [execution #38](http://ci.hibernate.org/view/Parser/job/hibernate-hql-parser-master/38/) is the last one which actually ran the build. Maybe it's due to some update/back-up restore of the CI server back then? Unfortunately the job config history doesn't go back that far.

**Pull request merged**
