### PR TITLE
HQLPARSER-74 Upgrade Hibernate Search to 5.8.0.Final

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/HQLPARSER-74
 * https://hibernate.atlassian.net/browse/HQLPARSER-75

### CODE REVIEW

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by Sanne** [comment]
There seem to be some problems with Animal Sniffer. Since we now want to baseline on Java8 we could remove these checks?

**Comment by Sanne** [comment]
Otherwise looks good.
Remember to test with `./gradlew build`, not just `./gradlew test`.

**Comment by gsmet** [comment]
Yeah... Still struggling to find the right targets with Gradle... Will fix.

**Comment by gsmet** [comment]
@Sanne I pushed an additional commit to upgrade the animal sniffer configuration. I would say let's keep it considering it might be useful in the future.

**Comment by Sanne** [comment]
> I would say let's keep it considering it might be useful in the future.

+1 Even better.

**Comment by Sanne** [comment]
merged! thanks

**Pull request merged**
